cornetto_defs(D) :-
D = [ 
'name'-'definition',
'mf'-'pronominal gender is m (masculine)- grammatical gender is f (feminine)',
'mfn'-' pronominal gender is  m (masculine) or f (feminine) depending on the biological gender, or n (neuter) - grammatical gender is n (neuter)',
'fn'-'pronominal gender is feminine (f) - grammatical gender is neuter (n)',
'mn'-'pronominal gender is m (masculine) - grammatical gender is n (neuter)',
'm_f'-'pronominal gender is m (masculine) or f (feminine) depending on the biological gender',
'action'-'Action verbs are verbs that describe actions and things taking place rather than states. Unlike most stative verbs, an action verb can usually be used in the progressive aspect, which is used for actions that are in progress.',
'process'-'refers to phenomenon  marked by changes through a series of states',
'state'-'refers to situations or conditions that are static',
'reference'-'attribute dealing with the type of noun, like common and proper',
'combiWord'-'sense examples and multiword expressions are considered as combinations of a head word and one or more combination words (combiWords).',
'synsetRelation'-'synsetRelation is a class representing the oriented relationship between Synset instances.',
'reltype'-'synset relation type refers to the type of relationship that exists between two synsets within one wordNet or between different wordNets.',
'MonolingualExternalRef'-'Monolingual External Ref is a class representing the relationship between a Sense or a Synset instance and an external system.',
'definition'-'Representation of a concept by a descriptive statement which serves to differentiate it from related concepts.',
'dancomp'-'complement headed by "dan" which is in Dutch the conjunction for introducing comparative clauses',
'whclause'-'complement headed by a WH-word like waarom (why), waar (where) , etc.',
'adverbialUsage'-'property of an adjective to be used also as an adverb (yes) or only as an adjective (no)',
'intransitive'-'Refers to a verb that does not take a direct object- that is, to a verb that does not express an action which directly affects another person or thing',
'semanticFeatureSet'-'a set of semantic properties which describe - in a formal way - the meaning of a verb. The set consists of the following features : transitive, intransitive, ditransitive, dynamic, cognitive, control, state, spatial',
'mass'-'Designation of a term or word that is not countable and cannot generally be used with the indefinite article or in the plural.',
'Morphology'-'The study of the structure and constituency of individual words.',
'Pragmatics'-'The study of the use of language in terms of the context in which it is spoken.',
'Semantics'-'The study of the meaning of linguistic structures.',
'Syntax'-'"The study of grammatical relations between words and other units within a sentence" (Concise Oxford Dictionary of Linguistics). To be distinguished from morphology, which applies to units smaller than the word.',
'abstract'-'Properties or qualities as distinguished from any particular embodiment of the properties/ qualities in a physical medium. Instances of Abstract can be said to exist in the same sense as mathematical objects such as sets and relations, but they cannot exist at a particular place and time without some physical encoding or embodiment. [SUMO 2010]',
'noun'-'word that can be combined with a demonstrative pronoun, while it is not a word form of another part of speech',
'common'-'Noun that signifies a non-specific member of a group.',
'proper'-'Noun that is the name of a specific individual, place, or object.',
'adjective'-'word characterizing an independent entity like a noun or its equivalent, while it is not a word form of another part of speech',
'verb'-'word that can be conjugated when combined with other words or groups of words in a sentence',
'abbreviation'-'indication that a word resulted by leaving out characters of a longer word or words, keeping the original meaning, while the resulting word is not considered a proper noun nor behaves as a common noun',
'partOfSpeech'-'A category assigned to a word based on its grammatical and semantic properties.',
'LexicalEntry'-'Container to represent the LMF Lexical Entry Class which represents a lexeme in a given language',
'pronominalAndGrammaticalGender'-'grammatical gender refers to the noun classification system that divides  common nouns in classes like feminine, neuter and masculine-  proniminal gender is the gender of the pronoun that refers to a noun- these types of gender are related but not identical. In Dutch, the pronominal gender may be determined by the grammatical or biological gender. In the Dutch language variant used in the Netherlands, however, (as opposed to Belgian Dutch) the feminine pronoun seems to disappear in favour of the masculine gender.',
'WordForms'-'WordForm Word Form is a Form subclass representing a form that a lexeme can take when used in a sentence or a phrase. So, Word Form class can manage simple lexemes, compounds and multi-word expressions.',
'RelatedForm'-'Related Form is a Form subclass representing a word form or a morph that can be related to the Lexical Entry in one of a variety of ways (e.g. Derivation, root). The Related Form can be typed. There is no assumption that the Related Form is associated with the Sense class in the Lexical Entry.',
'formType'-'Indication whether the form is a full form or an abbreviated form',
'full'-'full form (i.e. The form is not abbreviated)',
'writtenForm'-'representation of the written string of a form',
'formVariant'-'Variants with different written spelling and pronunciation.',
'spellingVariant'-'Variants with different written spelling but with the same pronunciation.',
'zero-derivation'-'The creation of a word from an existing word of a different word class without any change in form.',
'x-compound'-'idiomatic compound',
'complement'-' A noun phrase that follows a copula or similar verb, as for example an idiot in the sentence He is an idiot. - A clause that serves as the subject or direct object of a verb or the direct object of a preposition, as for example that he would be early in the sentence I hoped that he would be early.',
'oblprep'-'obligatory complement headed by a  fixed preposition',
'factive'-'complement headed by the Dutch factive complementizer "dat"',
'BE_IN_STATE'-'A relation between two concepts where concept A is qualified by concept B (cf. STATE_OF)',
'CAUSES'-'A relation between two concepts where concept B comes into existence as a result of concept A (cf. IS_CAUSED_BY)',
'CO_AGENT_INSTRUMENT'-'A relation between two concepts where concept B is the instrument used by concept A in a certain action. (cf. CO_INSTRUMENT_AGENT)',
'CO_AGENT_PATIENT'-'A relation between two concepts where concept B is the patient undergoing an action carried out by concept A. (cf. CO_PATIENT_AGENT)',
'CO_AGENT_RESULT'-'A relation between two concepts where concept B is the result of an action carried out by concept A. (cf. CO_RESULT_AGENT)',
'CO_INSTRUMENT_AGENT'-'A relation between two concepts where concept A is the instrument used by concept B for a certain action. (cf. CO_AGENT_INSTRUMENT)',
'CO_INSTRUMENT_PATIENT'-'A relation between two concepts where concept B undergoes an action for which the instrument expressed by concept A is used. (cf. CO_PATIENT_INSTRUMENT)',
'CO_INSTRUMENT_RESULT'-'A relation between two concepts where concept B is the result of an action carried out by the instrument expressed by concept A. (cf. CO_RESULT_INSTRUMENT)',
'CO_PATIENT_AGENT'-'A relation between two concepts where concept B undergoes an action carried out by concept A. (cf. CO_AGENT_PATIENT)',
'CO_PATIENT_INSTRUMENT'-'A relation between two concepts where concept A undergoes an action for which the instrument expressed by concept A is used. (cf. CO_INSTRUMENT_PATIENT)',
'CO_RESULT_AGENT'-'A relation between two concepts where concept A is the result of an action carried out by concept B. (cf. CO_AGENT_RESULT)',
'CO_RESULT_INSTRUMENT'-'A relation between two concepts where concept A is the result of an action for which the instrument expressed by concept B is used. (cf. CO_INSTRUMENT_RESULT)',
'CO_ROLE'-'A relation between two concepts where one concept undergoes an action in which the other concept is involved (bidirectional).',
'EQ_BE_IN_STATE'-'A relation between two concepts in two different languages where concept A is qualified by concept B (cf. EQ_IS_STATE_OF)',
'EQ_CAUSES'-'A relation between two concepts in two different languages where concept A causes concept B. (cf. EQ_IS_CAUSED_BY)',
'EQ_CO_ROLE'-'A relation between two concepts in two languages where one concept undergoes an action in which the other concept is involved (bidirectional).',
'EQ_HAS_HOLONYM'-'A relation between two concepts in two languages where concept A makes up a part of concept B. (cf. EQ_HAS_MERONYM)',
'EQ_HAS_HYPERONYM'-'A relation between two concepts in two different languages where concept A is a type of concept B. (cf. EQ_HAS_HYPONYM)',
'EQ_HAS_HYPONYM'-'A relation between two concepts in two languages where concept B is a type of concept A. (cf. EQ_HAS_HYPERONYM)',
'EQ_HAS_MERONYM'-'A relation between two concepts in two different languages where concept B makes up a part of concept A. (cf. EQ_HAS_HOLONYM)',
'EQ_HAS_SUBEVENT'-'A relation between two concepts in two different languages where concept B takes place during or as part of concept A, and whenever concept B takes place, concept A takes place. (cf. EQ_IS_SUBEVENT_OF)',
'EQ_INVOLVED'-'A relation between two concepts in two different languages where concept B is typically involved in the action or event expressed by concept A. (cf. EQ_ROLE)',
'EQ_IS_CAUSED_BY'-'A relation between two concepts in two different languages where concept B causes concept A. (cf. EQ_CAUSES)',
'EQ_IS_STATE_OF'-'A relation between two concepts in two different languages where concept B is qualified by concept A. (cf. EQ_BE_IN_STATE)',
'EQ_IS_SUBEVENT_OF'-'A relation between two concepts in two different languages where concept A takes place during or as part of concept B, and whenever concept A takes place, concept B takes place. (cf. EQ_HAS_SUBEVENT)',
'EQ_NEAR_SYNONYM'-'A relation between two concepts in two different languages where concept A and concept B are similar in meaning and are possible translations of each other. (cf. EQ_SYNONYM)',
'EQ_ROLE'-'A relation between two concepts in two different languages where concept A is typically involved in the action or event expressed by concept B. (cf. EQ_INVOLVED)',
'EQ_SYNONYM'-'A relation between two concepts in two different languages where concept A and concept B are translation equivalents. (cf. EQ_NEAR_SYNONYM)',
'EQ_UNSPECIFIED'-'A relation between two concepts in two different languages where concept A is strongly associated with concept B but no proper relation has been defined between the two.',
'FUZZYNYM'-'A relation between two concepts where concept A is strongly associated with concept B but no proper relation has been defined between the two.',
'HAS_HOLO_LOCATION'-'A relation between two concepts where concept A is a place located in concept B. (cf. HAS_MERO_LOCATION)',
'HAS_HOLO_MADEOF'-'A relation between two concepts where concept B is made of concept A. (cf. HAS_MERO_MADEOF)',
'HAS_HOLO_MEMBER'-'A relation between two concepts where concept A is a member/ element of concept B. (cf. HAS_MERO_MEMBER)',
'HAS_HOLO_PART'-'A relation between two concepts where concept A is a component of concept B. (cf. HAS_MERO_PART)',
'HAS_HOLO_PORTION'-'A relation between two concepts where concept B is an amount/piece/portion of concept A. (cf. HAS_MERO_PORTION)',
'HAS_HOLONYM'-'A relation between two concepts where concept A makes up a part of concept B. (cf. HAS_MERONYM)',
'HAS_HYPERONYM'-'A relation between two concepts where concept A is a type of concept B. (cf. HAS_HYPONYM)',
'HAS_HYPONYM'-'A relation between two concepts where concept B is a type of concept A. (cf. HAS_HYPERONYM)',
'HAS_MERO_LOCATION'-'A relation between two concepts where concept A is a place located in concept B. (cf. HAS_HOLO_LOCATION)',
'HAS_MERO_MADEOF'-'A relation between two concepts where concept A is made of concept B. (cf. HAS_HOLO_MADEOF)',
'HAS_MERO_MEMBER'-'A relation between two concepts where concept B is a member/ element of concept A. (cf. HAS_HOLO_MEMBER)',
'HAS_MERO_PART'-'A relation between two concepts where concept B is a component of concept A. (cf. HAS_HOLO_PART)',
'HAS_MERO_PORTION'-'A relation between two concepts where concept A is an amount/piece/portion of concept B. (cf. HAS_HOLO_PORTION)',
'HAS_MERONYM'-'A relation between two concepts where concept B makes up a part of concept A. (cf. HAS_HOLONYM)',
'HAS_SUBEVENT'-'A relation between two concepts where concept B takes place during or as part of concept A, and whenever concept B takes place, concept A takes place. (cf. IS_SUBEVENT_OF)',
'HAS_XPOS_HYPERONYM'-'A relation between two concepts of different part of speech where concept B is a type of concept A. (cf. HAS_XPOS_HYPONYM)',
'HAS_XPOS_HYPONYM'-'A relation between two concepts of different part of speech where concept B is a type of concept A. (cf. HAS_XPOS_HYPERONYM)',
'IN_MANNER'-'A relation between two concepts where concept B qualifies the manner in which an action or event expressed by concept A takes place. (cf. MANNER_OF)',
'INVOLVED'-'A relation between two concepts where concept B is typically involved in the action or event expressed by concept A. (cf. ROLE)',
'INVOLVED_AGENT'-'A relation between two concepts where concept B is typically the agent of the action expressed by concept A. (cf. ROLE_AGENT)',
'INVOLVED_DIRECTION'-'A relation between two concepts where concept B is typically the direction or location of the action or event expressed by concept A. (cf. ROLE _DIRECTION)',
'INVOLVED_INSTRUMENT'-'A relation between two concepts where concept B is typically the instrument necessary for the action or event expressed by concept A. (cf. ROLE _INSTRUMENT)',
'INVOLVED_LOCATION'-'A relation between two concepts where concept B is typically the location where the action or event expressed by concept A takes place. (cf. ROLE _LOCATION)',
'INVOLVED_PATIENT'-'A relation between two concepts where concept B is typically the patient undergoing an action or event expressed by concept A. (cf. ROLE _PATIENT)',
'INVOLVED_RESULT'-'A relation between two concepts where concept B comes into existence as a result of concept A. (cf. ROLE _RESULT)',
'INVOLVED_SOURCE_DIRECTION'-'A relation between two concepts where concept B is the place from where the action or event expressed by concept A begins/starts/happens. (cf. ROLE _SOURCE_DIRECTION)',
'INVOLVED_TARGET_DIRECTION'-'A relation between two concepts where concept B is the place where the action or event expressed by concept A leads to. (cf. ROLE _TARGET_DIRECTION)',
'IS_CAUSED_BY'-'A relation between two concepts where concept A comes into existence as a result of concept B. (cf. CAUSES)',
'IS_SUBEVENT_OF'-'A relation between two concepts where concept A takes place during or as part of concept B, and whenever concept A takes place, concept B takes place. (cf. HAS_SUBEVENT)',
'MANNER_OF'-'A relation between two concepts where concept A qualifies the manner in which an action or event expressed by concept B takes place. (cf. IN_MANNER)',
'NEAR_ANTONYM'-'A relation between two concepts where concept A has the opposite meaning to concept B.',
'NEAR_SYNONYM'-'A relation between two concepts where concept A and concept B are closely related in meaning but are not in the same synset.',
'ROLE'-'A relation between two concepts where concept A is typically involved in the action or event expressed by concept B. (cf. INVOLVED)',
'ROLE_AGENT'-'A relation between two concepts where concept A is typically the agent of the action expressed by concept B. (cf. INVOLVED _AGENT)',
'ROLE_DIRECTION'-'A relation between two concepts where concept A is typically the direction or location of the action or event expressed by concept B. (cf. INVOLVED _DIRECTION)',
'ROLE_INSTRUMENT'-'A relation between two concepts where concept A is the instrument necessary for the action or event expressed by concept B. (cf. INVOLVED _INSTRUMENT)',
'ROLE_LOCATION'-'A relation between two concepts where concept A is the location where the action or event expressed by concept B takes place. (cf. INVOLVED _LOCATION)',
'ROLE_PATIENT'-'A relation between two concepts where concept A is the patient undergoing an action or event expressed by concept B. (cf. INVOLVED _PATIENT)',
'ROLE_RESULT'-'A relation between two concepts where concept A comes into existence as a result of concept B. (cf. INVOLVED _RESULT)',
'ROLE_SOURCE_DIRECTION'-'A relation between two concepts where concept A is the place from where the action or event expressed by concept B begins/starts/happens. (cf. INVOLVED _SOURCE_DIRECTION)',
'ROLE_TARGET_DIRECTION'-'A relation between two concepts where concept A is the place where the action or event expressed by concept B leads to. (cf. INVOLVED_TARGET_DIRECTION)',
'STATE_OF'-'A relation between two concepts where concept B is qualified by concept A. (cf. BE_IN_STATE)',
'XPOS_FUZZYNYM'-'A relation between two concepts of different part of speech where concept A is strongly associated with concept B but no proper relation has been defined between the two.',
'XPOS_NEAR_ANTONYM'-'A relation between two concepts of different part of speech where concept A has the opposite meaning to concept B.',
'XPOS_NEAR_SYNONYM'-'A relation between two concepts of different part of speech where concept A and concept B are similar in meaning.',
'comparison'-'characterization of the degree of intensity of a specific feature by affixes (suffix, infix) or by suppletion',
'comparative'-'value expressing (via affix, suppletion) a higher than basic level of intensity of the named feature, while it is not the highest level.',
'superlative'-'value expressing (via affix or suppletion) the highest level of intensity of the named feature',
'comparisonType'-'The type of rule (i.e. regular,  irregular or mixed regular and irregular) which accounts for the forming of the comparative and superlative forms of adjectives',
'regular'-'Modification of adjectives to express relative degree by adding -er for the comparative and -st for the superlative form',
'mode'-'One of a set of distinctive forms that are used to signal modality. Modality is a facet of illocutionary point or general intent of a speaker, or a speaker\'s degree of commitment to the expressed proposition\'s believability, obligatoriness, desirability or reality.',
'infinitive'-'Mood cited as unmarked or base form.',
'tense'-'Property referring to the way the grammar marks the time at which the action denoted by the verb took place.',
'pastTense'-'Past tense is an absolute tense that refers to a time before the moment of utterance',
'pastParticiple'-'non-finite form of a verb expressing an event as completed',
'wordgroup'-'a wordgroup is a lemma that consists of one or more content words separated by space of hyphens',
'phrasal'-'a verb that is always combined with a preposition-like element (particle)',
'compderiv'-'A lexeme that is related to another lexeme by both a rule of derivation and a rule of composition',
'derivation'-'A lexeme that is related to another lexeme by a rule of derivation.',
'CanonicalForm'-'The canonical form is a representation of the example in a basic mode ("dictionary mode") with  not inflected verbs and singular nouns',
'irregular'-'Modification of adjectives to express relative degree using irregular forms such as "goed - beter - best".',
'mixed'-'Modification of adjectives to express relative degree using both regular and irregular forms such as in the case of "achterbaks - achterbakser - meest achterbaks."',
'morphoType'-'morphological type of a word refers to the internal morphological structure of a word',
'compderiv'-'A word that is morphologically related to other words by rules of both derivation and composition',
'colour'-'refers to colour',
'place'-'a point or an area on the Earth\'s surface or elsewhere',
'phyper'-'refers to physical or perceptive properties',
'emomen'-'referring to emotional or mental properties',
'quant'-'complement with optional specification of quantity',
'oblobj'-'complement with obligatory object "het"',
'attributive'-'An adjective that comes before a noun and not after a copula verb, like BE, SEEM, etc',
'predicative'-'indication that a word is realized at the position meant for the nonverbal part of a predicate or that of an adverb',
'attrpred'-'An adjective that can be used in both attributive and predicative position.',
'position'-'refers to the property of an adjective to be used in attributive or predicative position or in both positions',
'contraction'-'A lexical unit formed by a shortening of a word, syllable, or word group by omission of a sound or letter.',
'separability'-'refers to the characteristics of a verb whether it consists (or not consists) of a lexical core and a separable particle- the phenomenon of separable verbs is frequently found in Dutch, German and Hungarian',
'reflexivity'-'verb with an optional or obligatory reflexive pronoun',
'auxiliary'-'relation between a subordinate verb and the main verb',
'valency'-'The number of arguments controlled by a verbal predicate',
'transitivity'-'A property of verbs that relates to whether a verb can take direct objects and how many such objects a verb can take.',
'SubcategorizationFrame'-'Subcategorization Frame is a class representing one syntactic construction. A Subcategorization Frame instance is shared by all Lexical Entry instances that have the same syntactic behaviour in the same language. A Subcategorization Frame can inherit relationships and attributes from another more generic Subcategorization Frame by means of a reflexive link. Therefore, it is possible to integrate a hierarchical structure of Subcategorization Frame instances.',
'separable'-'A separable verb is a verb that is composed of a lexical core and a separable particle',
'unseparable'-'if a verb is unseparable , it does not consist of a lexical core and a separable particle but it appears always in one form',
'reflexive'-'voice for a construction where the semantic agent and patient are the same',
'optionalReflexive'-'reflexive voice is optional',
'mono'-'having one syntactic argument which is the subject',
'di'-'having two syntactic arguments of which one is the subject',
'tri'-'Ditransitivity (or Bitransitivity) is a term which describes a verb or clause which takes two objects and a subject argument',
'transitive'-'A verb which takes a direct object- that is, a verb that expresses an action which directly affects another person or thing.',
'constituent'-' structural element built around a main word (when there is one), formed of zero, one or more words and lacking the subject-predicate structure typical of clauses.',
'np'-' phrase headed by a noun',
'pp'-'phrase beginning by one or several prepositions and a complement such as a noun phrase',
's'-'A sequence of words capable of standing alone to make an assertion, ask a question, or give a command, usually consisting of a subject and a predicate containing a finite verb.',
'ap'-'phrase headed by an adjective',
'function'-'The grammatical relationship of one constituent to another within a syntactic construction.',
'objectComplement'-' A complement that is used to predicate a description of the direct object.',
'directObject'-' A noun, pronoun, or noun phrase whose referent receives the direct action of a verb.',
'indirectObject'-' A noun, pronoun, or noun phrase indicating the recipient or beneficiary of the action of a verb and its direct object.',
'prepositionalObject'-' The complement of a verb (noun, adjective) that is realized as a prepositional phrase and that can be questioned by a pronominal question, but not by an adverbial question. Verbs that take prepositional complements are called prepositional verbs in English, see Quirk et al. (1972): A Grammar of Contemporary English, 12.19. In German, prepositional complements are often called "Präpositionalobjekt", see Helbig, Buscha (1996): Deutsche Grammatik, 13.3.3.5',
'specifyingObject'-'verb complement, NP specifying a quantity',
'complementizer'-' relation between a subordinating conjunction and a verb, which marks an embedded sentence of a complement type',
'dat'-'the embedded sentence is headed by the subordinating conjunction "dat" (in Dutch)',
'omte'-'the embedded sentence is headed by the subordinating conjunction "om te" (in Dutch- cf. "to" in English)',
'te'-'the embedded sentence is headed by the subordinating conjunction "te" (in Dutch, cf. "to" in English)',
'WH'-'the embedded sentence is headed by a question word or wh-word like waarom (why), wat (what), wanneer (when), etc.',
'hoe'-'the embedded sentence is headed by the subordinating conjunction "hoe" (in Dutch- cf. "how" in English)',
'of'-'the embedded sentence is headed by the subordinating conjunction "of" (in Dutch- cf. "whether" in English)',
'stcognt1'-'refers to a verb concept with the following semantic features:intransitive, dynamic, control, cognitive',
'stcognt2'-'refers to a verb concept with the following semantic features: transitive, dynamic, control, cognitive',
'stcognt3'-'refers to a verb concept with the following semantic features:ditransitive, dynamic, control, cognitive',
'state1'-'refers to a verb concept with the following semantic features: state, intransitive',
'state2'-'refers to a verb concept with the following semantic features: state, transitive',
'state3'-'refers to a verb concept with the following semantic features: state, ditransitive',
'process1'-'refers to a verb concept with the following semantic features:intransitive, dynamic',
'process2'-'refers to a verb concept with the following semantic features:intransitive, dynamic',
'process3'-'refers to a verb concept with the following semantic features:ditransitive, dynamic',
'prmvmt1'-'refers to a verb concept with the following semantic features:intransitive, dynamic, spatial',
'prmvmt2'-'refers to a verb concept with the following semantic features: transitive, dynamic, spatial',
'prmvmt3'-'refers to a verb concept with the following semantic features:ditransitive, dynamic, spatial',
'possess2'-'refers to a verb concept with the following semantic features: transitive, attributive',
'possess3'-'refers to a verb concept with the following semantic features: ditransitive, attributive',
'prcognt1'-'refers to a verb concept with the following semantic features:intransitive, dynamic, cognitive',
'prcognt2'-'refers to a verb concept with the following semantic features:transitive, dynamic, cognitive',
'prcognt3'-'refers to a verb concept with the following semantic features:ditransitive, dynamic, cognitive',
'location1'-'refers to a verb concept with the following semantic features:intransitive, state, spatial',
'location2'-'refers to a verb concept with the following semantic features: transitive, spatial',
'mvmt1'-'refers to a verb concept with the following semantic features:intransitive, dynamic, control, spatial',
'mvmt2'-'refers to a verb concept with the following semantic features:transitive, dynamic, control, spatial',
'mvmt3'-'refers to a verb concept with the following semantic features:ditransitive, dynamic, control, spatial',
'echprod3'-'refers to a verb concept with the following semantic features:ditransitive, dynamic, control, attributive',
'echprod2'-'refers to a verb concept with the following semantic features: transitive, dynamic, control, attributive',
'action1'-'refers to a verb concept with the following semantic features:intransitive, dynamic, control',
'action2'-'refers to a verb concept with the following semantic features:transitive, dynamic, control',
'action3'-'refers to a verb concept with the following semantic features::ditransitive, dynamic, control',
'cognt1'-'refers to a verb concept with the following semantic features: intransitive, dynamic,control, cognitive',
'cognt2'-'refers to a verb concept with the following semantic features: transitive, dynamic,control, cognitive',
'cognt3'-'refers to a verb concept with the following semantic features:ditransitive, dynamic,control, cognitive',
'TextualForm'-'The textual form is an representation of an example as a fully inflected sentence- if it is combined with a canonical form, it is an illustration of the latter in a broader context.',
'idiom'-'a group of words in a fixed order that have a particular meaning that is different from the meaning of each word understood on its own',
'term'-' A verbal designation of a general concept in a specific subject field.',
'proverb'-'a brief popular axiom or saying',
'lexicalCollocation'-'a collocation (a combination of frequently co-occurrung words ) of two or more content words , i.e. nouns , verbs and adjectives and adverbs- collocations are syntactically fixed and semantically transparent',
'grammaticalCollocation'-'a collocation (a combination of frequently co-occurrung words ) of  function words (e.g a preposition or determiner) and content words  (i.e. a noun, verb, adjective or adverb). collocations are syntactically fixed and semantically transparent.',
'pragmaticFormula'-'a combination of words used repeatedly and always in the same form.  They are "highly conventionalized prepatterned expressions whose occurrence is tied to more or less standardized communication situations" (Coulmas, F. (1981) Conversational Routine)',
'properName'-'a noun that is the name of a specific individual, place, or object',
'slogan'-'a memorable phrase often used in a political, commercial, religious, and or other context as a repetitive expression of an idea or purpose (en.wikipedia.org/wiki/slogan)',
'SenseExample'-'SenseExample is a class used to illustrate the particular meaning of a Sense instance. A Sense can have zero to many examples.',
'freeCombination'-'a free word combination which is semantically completely transparent and syntactically not fixed',
'expressionType'-'expression types refer to a range of subtypes in accordance with the degree of semantic non-compositionalit and syntactic fixedness of the multiword expression',
'variantType'-'Refers to whether the variant form is different with regard to spelling (i.e. Spelling variant) or pronunciation (i.e. form variant)',
'acronym'-'An abbreviation made up of the initial letters of the components of the full form of the designation or from syllables of the full form and pronounced syllabically.',
'compound'-'A lexical unit that combines two or sometimes more different words, frequently such that the sense of the new lexical unit is not clearly derivable from the combination of its parts.',
'shortening'-'A word formed by the shortening of another word or word group by omission of a sound or letter.',
'Sense'-'One of zero to many meanings or concepts associated with a given head word in a lexical entry.',
'style'-'the way in which something is said or written.',
'archaic'-'A term or lexeme no longer in ordinary use, though retained for special purposes.',
'oldfashioned'-'A term or lexeme that has fallen from fashion, but the meaning of which is readily recognizable.',
'neologism'-'A newly coined term.',
'belg'-'used for words that are more frequently used in Belgian Dutch than in Dutch as uesd the Netherlands',
'derivation'-'Change in the form of a linguistic unit, usually modification in the base/root or affixation to create a new word.',
'Lemma'-'Base form a word or term that is used as the formal entry in a dictionary.',
'preposition'-'Preposition [prep] contains non-inflecting prepositional flexemes, which have the lexical category of case, indicating the subcategorisation properties of the preposition, and which do not occur with non-postprepositional forms of pronouns. Grammatical categories of preposition [prep]: case (http://www.isocat.org/datcat/DC-2720), vocalicity (http://www.isocat.org/datcat/DC-2748) (optional).',
'countability'-'Countability is motivated by the semantic distinction between object and substance reference.',
'formal'-'A broad term for speech or writing marked by an impersonal, objective, and precise use of language.',
'slang'-'An extremely informal register of a word, term, or text that is used in spoken and everyday language and less commonly in documents.',
'offensive'-'Register that expresses a situation that people should avoid because it is extremely offensive or embarrassing.',
'vulgar'-'Register of a term or text type that can be characterized as profane or socially unacceptable.',
'domain'-'area of activity, interest, or knowledge',
'count'-'noun referring to one or several concepts that may be counted',
'fixprep'-'optional complement headed by a fixed preposition',
'prep'-'The complement of a verb (noun, adjective) that is realized as a prepositional phrase and that can be questioned by a pronominal question, but not by an adverbial question. Verbs that take prepositional complements are called prepositional verbs in English, see Quirk et al. (1972): A Grammar of Contemporary English, 12.19. In German, prepositional complements are often called "Pr+ñpositionalobjekt", see Helbig, Buscha (1996): Deutsche Grammatik, 13.3.3.5',
'psmodnoun'-'Post-modifying noun complement',
'toinf'-'complement with "te"-infinitive',
'omtoinf'-'complement with "om te"-infinitive',
'SenseRelation'-'Sense Relation is a class representing the oriented relationship between Senses instances',
'SenseGroup'-'A sense-group is a set of meanings of a word that are semantically close and therefore difficult to discriminate both for humans and machines (source: DutchSemCor-project).',
'relationType'-'relation type specifies the type of relation between two elements',
'co-hyponyms'-'senses of one word that belong to synsets that have the same hypernym',
'co-relations'-'senses of one word that belong to synsets that have a direct semantic relation, e.g. NEAR_SYNONYM, SUBEVENT, RESULT, PART, etc.',
'co-synonyms'-'senses of one word that belong to synsets that have more than one synonym in common, i.e. in addition to the lemma itself there is at least lemma that occurs in both synsets.',
'co-annotations'-'senses of one word that were both assigned to a single token in the corpus during manual sense-tagging in the DutchSemCor-project.',
'chronology'-'the use of a word is related to a certain period in time',
'connotation'-'A connotation is a commonly understood subjective cultural or emotional association that some word or phrase carries, in addition to the word\'s or phrase\'s explicit or literal meaning, which is its denotation.',
'geography'-'Regional occurrence of a word',
'informal'-'Language use characterized by spontaneous speech.',
'euphemistic'-'Innocuous word, name, or phrase that replaces an offensive or suggestive one.',
'jocular'-'Fond of or characterized by joking- humorous or playful.',
'pejorative'-'A word or grammatical form that connotes negativity and expresses a contempt or distaste.',
'uncount'-'An uncountable noun is a noun with the property that any quantity of it is treated as an undifferentiated unit, rather than as something with discrete subsets.',
'count_uncount'-'Nouns that can be both countable or uncountable according to their different meanings.',
'coll'-'A collective noun is the name of a number (or collection) of people or things taken together and spoken of as one whole.',
'pluraleTantum'-'Plurale Tantum is a noun that appears only in the plural form and does not have a singular variant for referring to a single object.',
'semanticType'-'a semantic Type is part of a set of values that categorizes concepts in a given domain according to their semantic characteristics',
'animate'-'Perceived as alive.',
'artefact'-'refers to  physical entities constructed by man',
'concrete'-'A concrete object is an object which exists at a particular time or place. It is the opposite of abstract.',
'concrother'-'refers to concepts which are concrete, but not substance or artefact',
'dynamic'-'abstract concept involving change or  internal stages',
'human'-'animate and human being (cf.  nonhuman)',
'institute'-'groups and organizations that can act as an agent',
'measure'-'nonanimate and a unit of length, measure, distance, money etc.',
'nondynamic'-'abstract concept not involving change or internal stages',
'nonhuman'-'animate but not human (cf. human)',
'substance'-'nonanimate and material substances, incl. natural kinds',
'time'-'specifying a period or moment in time',
'semanticShifts'-'a semantic shift refers to a process of meaning extension following a -usually systematic- shift between semantic types',
'm'-'grammatical and pronominal gender are m (masculine)',
'f'-'grammatical and pronominal gender are f (feminine)',
'n'-'grammatical and pronominal gender are n (neuter)',
'LexicalResource'-'Lexical Resource is a class representing the entire resource. Lexical Resource occurs once and only once. The Lexical Resource instance is a container for one or more lexicons.',
'Lexicon'-'Lexicon may also be used as a general term covering different types of lexical resources such as dictionaries, wordnets, lexicons, etc.',
'GlobalInformation'-'Global Information is a class representing administrative information and other general attributes. There is an aggregation relationship between the Lexical Resource class and the Global Information class in that the latter describes the administrative information and general attributes of the entire resource. The Global Information class does not allow subclasses.',
'synset'-'A synonym set- a set of words that are interchangeable in some context without changing the truth value of the preposition in which they are embedded.',
'polarity'-'polarity refers to the property of a word in a particular sense to express attitude. Usually there are 3 values: positive , negative or neutral (no) attitude',
'positive'-'the property of a word (sense) to express a positive attitude',
'negative'-'the property of a word (sense) to express a negative attitude',
'external Reference'-'Reference to a particular node of an external descriptive system.',
'external System'-'Reference to an external descriptive system.',
'article'-'Definite article which is used for singular elements',
'grammaticalNumber'-'Grammatical category for the variation in form of nouns, pronouns, and any words agreeing with them, depending on how many persons or things are referred to',
'plural'-'Value that expresses more than one element',
'singular'-'Value that expresses one element',
'syntacticArgument'-'Syntactic Argument is a class representing an argument of a given Subcategorization Frame. A Syntactic Argument can be linked recursively to a Subcategorization Frame instance in order to describe deeply complex arguments. Syntactic Argument allows the connection with a semantic argument by means of a SynSemArgMap instance.',
'syntacticBehaviour'-'Syntactic Behaviour is a class representing one of the possible behaviours of a lexeme. The Syntactic Behaviour instance is attached to the Lexical Entry instance and optionally to the Sense instance. The presence in a given lexicon of one Syntactic Behaviour instance for a lexical entry means that this lexeme can have this behaviour in the language of the lexicon. Syntactic description is optional, so it is possible to describe morphology and semantics without any syntactic description. Lexical Entry, Syntactic Behaviour and Sense instances form a triangle representing Morphology, Syntax and Semantics. Detailed description of the syntactic behaviour of a lexical entry is defined by the Subcategorization Frame instance.'
].
